#!/bin/bash
# -ev negates the regular expression so it will not show up in the logfile window only
# for the file following the command(s). 
# -cS uses the color scheme set in multitail.conf for only the file follwing the command.
# -i specific file to tail.
# -wh window 2's only 12 lines high

# The order of these lines matter as each color scheme and regular expression are tied to
# the file that is being tailed. Everything before each -i is tied to the options before it.

confpath="mul.conf"

multitail --config $confpath \
-cS BanColor \
-t "WifiScan" \
-i scan.log \
